name: Email to Google Sheets

on:
  issues:
    types: [opened]

jobs:
  add-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Extract email from issue
        id: extract-email
        run: echo "::set-output name=email::$(echo '${{ github.event.issue.title }}' | sed 's/New subscription: //')"

      - name: Run script to add email to Google Sheets
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          EMAIL_TO_ADD: ${{ steps.extract-email.outputs.email }}
        run: node scripts/add-email-to-sheets.js